server:
  port: 8091
  servlet:
    context-path: /apigateway
spring:
#  API Gateway Properties
  cloud:
    gateway:
      routes:
        - id: apigateway
          uri: http://localhost:8091/
          predicates:
            - Path=/apigateway/**
        - id : student
          uri: http://localhost:9091/
          predicates :
            - Path=/student/**
          filters :
            - name : APIGatewayPostFilters
        - id: employee
          uri: http://localhost:9092/
          predicates:
              - Path=/employee/**
          filters:
              - name: APIGatewayPreFilters
      default-filters:
        - name : APIGatewayGlobalFilters
  application:
    name: apigateway
  jmx:
    enabled: false
    default-domain: apigateway
  flyway:
    enabled: true
    baseline-description: API-GATEWAY
    baseline-version: 0
    table: JG_API_GATEWAY_VERSION
    baseline-on-migrate: true
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.Oracle12cDialect
    open-in-view: false
    properties:
      release_mode: after_transaction
      agressive_release: true
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
#    # Oracle DB
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: SPRINGLEARN
    password: SPRINGLEARN
    hikari:
       minimum-idle : 5
       maximum-pool-size : 20
       idle-timeout : 30000
       pool-name : JGGATEWAY-CP
       #If there are more than minimumIdle number of connections the housekeeper will close connections that have been idle for longer than idleTimeout
       max-lifetime : 2000000
       connection-timeout : 30000
logging:
  level:
    com.zaxxer.hikari.HikariConfig : error
