-- ROUTER TABLE
CREATE TABLE APIM_API_ROUTE (
	API_KEY NUMBER(19) NOT NULL,
	API_NAME VARCHAR2(50) NOT NULL,
	REQUEST_URI VARCHAR2(1024) NOT NULL,
	TARGET_URL VARCHAR2(2048) NOT NULL,
	CONSTRAINT AR_PK PRIMARY KEY (API_KEY) ENABLE
);

ALTER TABLE MXAPIM_API_ROUTE ADD CONSTRAINT APIM_API_ROUTE_UK UNIQUE (API_NAME);

-- Generate ID using sequence and trigger
CREATE SEQUENCE AR_SEQ START WITH 1 INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 20;

CREATE OR REPLACE TRIGGER AR_SEQ_TR
 BEFORE INSERT ON APIM_API_ROUTE FOR EACH ROW
 WHEN (NEW.API_KEY IS NULL)
BEGIN
 SELECT AR_SEQ.NEXTVAL INTO :NEW.API_KEY FROM DUAL;
END;
/
